    
[build]
  command = "echo ANGULAR_WORKSPACE_FILE=$ANGULAR_WORKSPACE_FILE && npx nx run storeApp:build --skip-nx-cache --configuration=production"
  publish = "dist/apps/storeApp"

[build.environment]
  NODE_VERSION = "18"
  ANGULAR_WORKSPACE_FILE="project.json" 
