[[plugins]]
package = "@netlify/angular-runtime"

[build]
  command = "nx build your-app-name --configuration=production"
  publish = "dist/apps/your-app-name"

[functions]
  directory = "netlify/functions"

  [build.environment]
  NODE_VERSION = "18"